call plug#begin('~/.vim/plugged')
	Plug 'easymotion/vim-easymotion'
	Plug 'tomtom/tcomment_vim'
	Plug 'rust-lang/rust.vim'	
	Plug 'rhysd/vim-clang-format'
	Plug 'kana/vim-operator-user'
call plug#end()

inoremap <silent> jj <ESC>
set autoindent
set tabstop=4
set shiftwidth=4
set whichwrap=h,l
set number
set hlsearch

hi comment ctermfg=gray

" Rust format
syntax enable
filetype plugin indent on
let g:rustfmt_autosave = 1

" C format
" let g:clang_format#code_style = 'Google'
" let g:clang_format#auto_format = 1
au FileType c set tabstop=2
au FileType c set shiftwidth=2

" Easy motion
" Move to {char}
map <Space>f <Plug>(easymotion-bd-f)
" Move to line
map <Space>l <Plug>(easymotion-bd-jk)
" Move to word
map <Space>w <Plug>(easymotion-bd-w)
